name: publish

on:
  push:
    paths:
      - powershell-az.psd1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          Publish-Module -Path .\ -NuGetApiKey $env:POWERSHELLGALLERY_KEY
        shell: pwsh
        env:
          POWERSHELLGALLERY_KEY: ${{ secrets.POWERSHELLGALLERY_KEY }}